image: mcr.microsoft.com/dotnet/core/sdk:latest

stages:
  - update_libraries
  - test
  - build

variables:
  # Define your variables here, such as project name, etc.

before_script:
  - dotnet restore

update_libraries:
  stage: update_libraries
  script:
    - dotnet tool install -g dotnet-outdated
    - dotnet outdated --prerelease
    # Use dotnet-outdated tool or other method to update packages
  only:
    - schedules

test:
  stage: test
  script:
    - dotnet test
  tags:
    - dotnet

build:
  stage: build
  script:
    - dotnet build
  artifacts:
    paths:
      - SalesBE/WebAPI/bin/Debug/net6.0/
  tags:
    - dotnet
